<a href="https://colab.research.google.com/github/lekshmi29-lx/DSA_B7_Note-1/blob/main/Read_Data_from_Various_Sources.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Reading Data from Various Sources**

Data can come from CSV, Excel, JSON, SQL Databases, APIs, Big Data sources.

Python libraries: *pandas.read_csv(), pandas.read_excel(), pd.read_json(), sqlalchemy,* etc.

**Array**

Arrays are homogeneous data structures (same type of elements).

In Python: *numpy.array()* is used for fast computation.

Useful for mathematical operations, linear algebra, statistics.

**DataFrame**

Two-dimensional labeled data structure (rows + columns).

In Pandas: *pd.DataFrame().*

**Series**

A one-dimensional labeled array in Pandas.

Holds data of any type (int, float, string, etc.).

Example: *pd.Series([10, 20, 30], index=['a','b','c'])*.

Useful for time-series and single column analysis.

Reading from xlsx

In [ ]:
import pandas as pd

employee = pd.read_excel("/content/employee.xlsx",header = 1,sheet_name="Managers")
employee

  emp_id     name   department  hire_date  salary  full_time
0  E1001  Lekshmi    Marketing 2018-03-12   80000      False
1  E1002  Aswathi  Engineering 2019-07-23   85000       True
2  E1003   Sandra           HR 2020-01-15   60000      False
3  E1004  Krishna      Finance 2017-11-30   65000       True
4  E1005     Sonu        Sales 2021-05-10   67000       True

In [ ]:
xlsheets = pd.ExcelFile("/content/employee.xlsx")
xlsheets.sheet_names

['Employee', 'Managers']

In [ ]:
employee = pd.read_excel('/content/employee.xlsx',header=1,sheet_name=None)
employee

{'Employee':   emp_id           name   department  hire_date  salary  full_time
 0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
 1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
 2  E1003    Priya Singh           HR 2020-01-15   60000      False
 3  E1004         Li Wei      Finance 2017-11-30   79000       True
 4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True,
 'Managers':   emp_id     name   department  hire_date  salary  full_time
 0  E1001  Lekshmi    Marketing 2018-03-12   80000      False
 1  E1002  Aswathi  Engineering 2019-07-23   85000       True
 2  E1003   Sandra           HR 2020-01-15   60000      False
 3  E1004  Krishna      Finance 2017-11-30   65000       True
 4  E1005     Sonu        Sales 2021-05-10   67000       True}

In [ ]:
dataset1 = employee["Employee"]
dataset1

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
2  E1003    Priya Singh           HR 2020-01-15   60000      False
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True

In [ ]:
dataset2 = employee["Managers"]
dataset2

  emp_id     name   department  hire_date  salary  full_time
0  E1001  Lekshmi    Marketing 2018-03-12   80000      False
1  E1002  Aswathi  Engineering 2019-07-23   85000       True
2  E1003   Sandra           HR 2020-01-15   60000      False
3  E1004  Krishna      Finance 2017-11-30   65000       True
4  E1005     Sonu        Sales 2021-05-10   67000       True

In [ ]:
dataset = pd.concat([dataset1,dataset2])
dataset

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
2  E1003    Priya Singh           HR 2020-01-15   60000      False
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True
0  E1001        Lekshmi    Marketing 2018-03-12   80000      False
1  E1002        Aswathi  Engineering 2019-07-23   85000       True
2  E1003         Sandra           HR 2020-01-15   60000      False
3  E1004        Krishna      Finance 2017-11-30   65000       True
4  E1005           Sonu        Sales 2021-05-10   67000       True

In [ ]:
full_time = dataset[dataset['full_time']== True]
full_time

  emp_id           name   department  hire_date  salary  full_time
0  E1001  Julia Roberts    Marketing 2018-03-12   72000       True
1  E1002   Ahmed Hassan  Engineering 2019-07-23   85000       True
3  E1004         Li Wei      Finance 2017-11-30   79000       True
4  E1005  Carlos Mendes        Sales 2021-05-10   67000       True
1  E1002        Aswathi  Engineering 2019-07-23   85000       True
3  E1004        Krishna      Finance 2017-11-30   65000       True
4  E1005           Sonu        Sales 2021-05-10   67000       True

In [ ]:
avg_department = dataset.groupby('department')['salary'].mean()
avg_department

department
Engineering    85000.0
Finance        72000.0
HR             60000.0
Marketing      76000.0
Sales          67000.0
Name: salary, dtype: float64

In [ ]:
dataset.to_excel('combined_employee.xlsx',index=False)

Read from CSV

In [ ]:
weather = pd.read_csv("/content/weather.csv")
weather

,date,station_id,temperature_c,humidity_pct,wind_speed_kmh,precip_mm
0,2025-07-01,WS100,29.5,65,12.4,0.0
1,2025-07-01,WS101,31.2,58,8.7,0.0
2,2025-07-01,WS102,28.9,72,5.2,1.3
3,2025-07-02,WS100,30.1,63,14.0,0.0
4,2025-07-02,WS101,32.0,55,10.1,0.0
5,2025-07-02,WS102,29.5,70,6.0,0.8
6,2025-07-03,WS100,28.0,68,11.3,2.5
7,2025-07-03,WS101,29.8,60,9.5,0.0
8,2025-07-03,WS102,27.7,75,4.8,3.1

In [ ]:
# print days where temperature greater than 30
days = weather[weather['temperature_c']>30]
days

,date,station_id,temperature_c,humidity_pct,wind_speed_kmh,precip_mm
1,2025-07-01,WS101,31.2,58,8.7,0.0
3,2025-07-02,WS100,30.1,63,14.0,0.0
4,2025-07-02,WS101,32.0,55,10.1,0.0

In [ ]:
# compute daily average humidity
daily_avg = weather.groupby('date')['humidity_pct'].mean()
daily_avg

date
2025-07-01    65.000000
2025-07-02    62.666667
2025-07-03    67.666667
Name: humidity_pct, dtype: float64

xml

In [ ]:
catalog = pd.read_xml("/content/library_catalog.xml")
catalog

,isbn,title,author,genre,publish_date,price
0,978-0143127550,The Martian,Andy Weir,Science Fiction,2014-10-28,9.99
1,978-0553386790,"Thinking, Fast and Slow",Daniel Kahneman,Psychology,2013-04-02,12.50
2,978-0062316097,The Alchemist,Paulo Coelho,Fiction,2014-04-15,8.99

In [ ]:
genres = catalog['genre']
genres

0    Science Fiction
1         Psychology
2            Fiction
Name: genre, dtype: object

Read from json

In [ ]:
movie = pd.read_json("/content/movies.json")
movie

,movie_id,title,year,genres,rating,votes
0,MV001,Inception,2010,"[Action, Sci‐Fi]",8.8,2100000
1,MV002,The Dark Knight,2008,"[Action, Crime, Drama]",9.0,2300000
2,MV003,Interstellar,2014,"[Adventure, Drama, Sci‐Fi]",8.6,1500000
3,MV004,The Matrix,1999,"[Action, Sci‐Fi]",8.7,1700000
4,MV005,Parasite,2019,"[Comedy, Drama, Thriller]",8.6,700000
5,MV006,Gladiator,2000,"[Action, Adventure, Drama]",8.5,1400000
6,MV007,Avengers: Endgame,2019,"[Action, Adventure, Drama]",8.4,1000000
7,MV008,The Shawshank Redemption,1994,[Drama],9.3,2400000
8,MV009,Pulp Fiction,1994,"[Crime, Drama]",8.9,1800000
9,MV010,Forrest Gump,1994,"[Drama, Romance]",8.8,1900000

In [ ]:
#High_rated = movie.groupby('title')['rating'].

In [ ]:
#highest rating movie
high_rated = movie.sort_values('rating',ascending=False).head(1)
high_rated

  movie_id                     title  year   genres  rating    votes
7    MV008  The Shawshank Redemption  1994  [Drama]     9.3  2400000

In [ ]:
#average rating by genre
Genre = movie.explode('genres')
Genre

  movie_id                     title  year     genres  rating    votes
0    MV001                 Inception  2010     Action     8.8  2100000
0    MV001                 Inception  2010     Sci‐Fi     8.8  2100000
1    MV002           The Dark Knight  2008     Action     9.0  2300000
1    MV002           The Dark Knight  2008      Crime     9.0  2300000
1    MV002           The Dark Knight  2008      Drama     9.0  2300000
2    MV003              Interstellar  2014  Adventure     8.6  1500000
2    MV003              Interstellar  2014      Drama     8.6  1500000
2    MV003              Interstellar  2014     Sci‐Fi     8.6  1500000
3    MV004                The Matrix  1999     Action     8.7  1700000
3    MV004                The Matrix  1999     Sci‐Fi     8.7  1700000
4    MV005                  Parasite  2019     Comedy     8.6   700000
4    MV005                  Parasite  2019      Drama     8.6   700000
4    MV005                  Parasite  2019   Thriller     8.6   700000
5    MV006                 Gladiator  2000     Action     8.5  1400000
5    MV006                 Gladiator  2000  Adventure     8.5  1400000
5    MV006                 Gladiator  2000      Drama     8.5  1400000
6    MV007         Avengers: Endgame  2019     Action     8.4  1000000
6    MV007         Avengers: Endgame  2019  Adventure     8.4  1000000
6    MV007         Avengers: Endgame  2019      Drama     8.4  1000000
7    MV008  The Shawshank Redemption  1994      Drama     9.3  2400000
8    MV009              Pulp Fiction  1994      Crime     8.9  1800000
8    MV009              Pulp Fiction  1994      Drama     8.9  1800000
9    MV010              Forrest Gump  1994      Drama     8.8  1900000
9    MV010              Forrest Gump  1994    Romance     8.8  1900000

In [ ]:
avg_rate = Genre.groupby('genres')['rating'].mean()
avg_rate

genres
Action       8.6800
Adventure    8.5000
Comedy       8.6000
Crime        8.9500
Drama        8.7625
Romance      8.8000
Sci‐Fi       8.7000
Thriller     8.6000
Name: rating, dtype: float64

In [ ]:
#count movie by year
count_year = movie.groupby('year')['title'].count()
count_year

year
1994    3
1999    1
2000    1
2008    1
2010    1
2014    1
2019    2
Name: title, dtype: int64

In [ ]:
review = pd.read_html("/content/review.html")
review[0]

,review_id,reviewer,restaurant,rating,comment,date
0,R001,Alice,The Spice Hub,4.5,Great flavors but a bit loud.,2025-06-20
1,R002,Bob,Sushi World,5.0,Fresh fish and perfect rice.,2025-06-22
2,R003,Chen,Pasta Palace,4.0,"Cozy place, generous portions.",2025-06-25

In [ ]:
len(review)

1

In [ ]:
review1 = review[0]

In [ ]:
high_rating = review1[review1['rating']>4.5]
print(high_rating)

  review_id reviewer   restaurant  rating                       comment  \
1      R002      Bob  Sushi World     5.0  Fresh fish and perfect rice.

         date
1  2025-06-22

**API**

When reading data from an API, the format of the data can vary. As seen from the output, the API returned a JSON object, which was then converted into a pandas DataFrame. Other APIs might return data in different formats like XML or CSV. You can use libraries like requests to fetch data from APIs and then use appropriate pandas functions like read_json, read_xml, or read_csv to load the data into a DataFrame depending on the format.

In [1]:
import requests
url ="https://disease.sh/v3/covid-19/countries"

response = requests.get(url)
data = response.json()
#data

In [ ]:
covid_df = pd.DataFrame(data)
covid_df.head()

,updated,country,countryInfo,cases,todayCases,deaths,todayDeaths,recovered,todayRecovered,active,...,tests,testsPerOneMillion,population,continent,oneCasePerPeople,oneDeathPerPeople,oneTestPerPeople,activePerOneMillion,recoveredPerOneMillion,criticalPerOneMillion
0,1757414676667,Afghanistan,"{'_id': 4, 'iso2': 'AF', 'iso3': 'AFG', 'lat':...",234174,0,7996,0,211080,0,15098,...,1390730,34125,40754388,Asia,174,5097,29,370.46,5179.32,0.0
1,1757414676659,Albania,"{'_id': 8, 'iso2': 'AL', 'iso3': 'ALB', 'lat':...",334863,0,3605,0,330233,0,1025,...,1941032,677173,2866374,Europe,9,795,1,357.59,115209.32,0.0
2,1757414676663,Algeria,"{'_id': 12, 'iso2': 'DZ', 'iso3': 'DZA', 'lat'...",272010,0,6881,0,183061,0,82068,...,230960,5093,45350148,Africa,167,6591,196,1809.65,4036.61,0.0
3,1757414676715,Andorra,"{'_id': 20, 'iso2': 'AD', 'iso3': 'AND', 'lat'...",48015,0,165,0,0,0,47850,...,249838,3225256,77463,Europe,2,469,0,617714.26,0.00,0.0
4,1757414676689,Angola,"{'_id': 24, 'iso2': 'AO', 'iso3': 'AGO', 'lat'...",107327,0,1937,0,103419,0,1971,...,1499795,42818,35027343,Africa,326,18083,23,56.27,2952.52,0.0

In [ ]:
covid_df.size

5313

In [ ]:
covid_df.shape

(231, 23)

In [ ]:
len(covid_df)

231

In [ ]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 231 entries, 0 to 230
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   updated                 231 non-null    int64
 1   country                 231 non-null    object
 2   countryInfo             231 non-null    object
 3   cases                   231 non-null    int64
 4   todayCases              231 non-null    int64
 5   deaths                  231 non-null    int64
 6   todayDeaths             231 non-null    int64
 7   recovered               231 non-null    int64
 8   todayRecovered          231 non-null    int64
 9   active                  231 non-null    int64
 10  critical                231 non-null    int64
 11  casesPerOneMillion      231 non-null    int64
 12  deathsPerOneMillion     231 non-null    int64
 13  tests                   231 non-null    int64
 14  testsPerOneMillion      231 non-null    int64
 15  population              231 non-null    int64
 16  continent               231 non-null    object
 17  oneCasePerPeople        231 non-null    int64
 18  oneDeathPerPeople       231 non-null    int64
 19  oneTestPerPeople        231 non-null    int64
 20  activePerOneMillion     231 non-null    float64
 21  recoveredPerOneMillion  231 non-null    float64
 22  criticalPerOneMillion   231 non-null    float64
dtypes: float64(3), int64(17), object(3)
memory usage: 41.6+ KB

In [ ]:
covid_info = covid_df[['country','cases','deaths','active','critical','recovered']]
covid_info

               country   cases  deaths  active  critical  recovered
0          Afghanistan  234174    7996   15098         0     211080
1              Albania  334863    3605    1025         0     330233
2              Algeria  272010    6881   82068         0     183061
3              Andorra   48015     165   47850         0          0
4               Angola  107327    1937    1971         0     103419
..                 ...     ...     ...     ...       ...        ...
226  Wallis and Futuna    3550       8    3104         0        438
227     Western Sahara      10       1       0         0          9
228              Yemen   11945    2159     662         0       9124
229             Zambia  349304    4069    3919         0     341316
230           Zimbabwe  266359    5740    1731        12     258888

[231 rows x 6 columns]

In [ ]:
covid_info.to_excel("covid.xlsx",index=False)

In [ ]:
url = "https://www.runnersworld.com/races-places/a20823734/these-are-the-worlds-fastest-marathoners-and-marathon-courses/"
tables = pd.read_html(url)
print(type(tables))

<class 'list'>

In [ ]:
len(tables)

8

In [ ]:
tables

[                             0            1          2               3
 0                       Runner  Finish Time  Pace/Mile        Marathon
 1        Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
 2       Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
 3   Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
 4       Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
 5       Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
 6       Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
 7     Deresa Geleta (Ethiopia)      2:02:38     4:40.6  Valencia, 2024
 8           John Korir (Kenya)      2:02:44     4:40.8   Chicago, 2024
 9    Birhanu Legese (Ethiopia)      2:02:48     4:41.0    Berlin, 2019
 10  Mosinet Geremew (Ethiopia)      2:02:55     4:41.3    London, 2019,
                                   0            1          2               3
 0                            Runner  Finish Time  Pace/Mile        Marathon
 1          Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
 2          Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
 3        Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
 4             Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
 5                               NaN          NaN        NaN             NaN
 6           Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
 7   Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
 8        Worknesh Degefa (Ethiopia)      2:15:51     5:10.9  Valencia, 2023
 9          Sutume Kebede (Ethiopia)      2:15:55     5:11.0     Tokyo, 2024
 10         Tigist Ketema (Ethiopia)      2:16:07     5:11.5     Dubai, 2024
 11         Rosemary Wanjiru (Kenya)      2:16:14     5:11.8     Tokyo, 2024
 12                              NaN          NaN        NaN             NaN,
                     0            1          2                 3
 0              Runner  Finish Time  Pace/Mile          Marathon
 1   Khalid Khannouchi      2:05:38     4:47.5      London, 2002
 2          Galen Rupp      2:06:07     4:48.6      Prague, 2018
 3           Ryan Hall      2:06:17     4:49.0      London, 2008
 4       Biya Simbassa      2:06:53     4:50.4    Valencia, 2024
 5   Dathan Ritzenhein      2:07:47     4:52.4     Chicago, 2012
 6        Conner Mantz      2:07:47     4:52.4     Chicago, 2023
 7       Leonard Korir      2:07:56     4:52.8   Amsterdam, 2019
 8       Clayton Young      2:08:00     4:52.9     Chicago, 2023
 9        CJ Albertson      2:08:17     4:53.6     Chicago, 2024
 10         Alex Maier      2:08:33     4:54.2  Dusseldorf, 2025,
                    0            1          2                           3
 0             Runner  Finish Time  Pace/Mile                    Marathon
 1       Emily Sisson      2:18:29     5:16.9               Chicago, 2022
 2      Keira D’Amato      2:19:12     5:18.6               Houston, 2022
 3        Betsy Saina      2:19:17     5:18.7                 Tokyo, 2024
 4       Deena Kastor      2:19:36     5:19.5                London, 2006
 5          Sara Hall      2:20:32     5:21.6  The Marathon Project, 2020
 6       Jordan Hasay      2:20:57     5:22.6               Chicago, 2017
 7   Shalane Flanagan      2:21:14     5:23.2                Berlin, 2014
 8     Joan Samuelson      2:21:21     5:23.5               Chicago, 1985
 9          Amy Cragg      2:21:42     5:24.3                 Tokyo, 2018
 10  Susanna Sullivan      2:21:56     5:24.8               Chicago, 2024,
                              0            1          2               3
 0                       Runner  Finish Time  Pace/Mile        Marathon
 1        Kelvin Kiptum (Kenya)      2:00:35     4:36.0   Chicago, 2023
 2       Eliud Kipchoge (Kenya)      2:01:09     4:37.2    Berlin, 2022
 3        Kelvin Kiptum (Kenya)      2:01:25     4:37.8    London, 2023
 4       Eliud Kipchoge (Kenya)      2:01:39     4:38.4    Berlin, 2018
 5   Kenenisa Bekele (Ethiopia)      2:01:41     4:38.5    Berlin, 2019
 6       Sisay Lemma (Ethiopia)      2:01:48     4:38.7  Valencia, 2023
 7        Kelvin Kiptum (Kenya)      2:01:53     4:38.9  Valencia, 2022
 8       Sabastian Sawe (Kenya)      2:02:05     4:39.4  Valencia, 2024
 9       Benson Kipruto (Kenya)      2:02:16     4:39.8     Tokyo, 2024
 10      Eliud Kipchoge (Kenya)      2:02:37     4:40.6    London, 2019
 11                         NaN          NaN        NaN             NaN,
                                   0            1          2               3
 0                            Runner  Finish Time  Pace/Mile        Marathon
 1          Ruth Chepngetich (Kenya)      2:09:56     4:57.4   Chicago, 2024
 2          Tigist Assefa (Ethiopia)      2:11:53     5:01.8    Berlin, 2023
 3        Sifan Hassan (Netherlands)      2:13:44     5:06.0   Chicago, 2023
 4             Brigid Kosgei (Kenya)      2:14:04     5:06.8   Chicago, 2019
 5          Ruth Chepngetich (Kenya)      2:14:18     5:07.3   Chicago, 2022
 6           Amane Beriso (Ethiopia)      2:14:58     5:08.9  Valencia, 2022
 7   Paula Radcliffe (Great Britain)      2:15:25     5:09.9    London, 2003
 8          Tigist Assefa (Ethiopia)      2:15:37     5:10.3    Berlin, 2022
 9          Ruth Chepngetich (Kenya)      2:15:37     5:10.3   Chicago, 2023
 10         Tigist Assefa (Ethiopia)      2:15:50     5:10.8    London, 2025,
                                     0            1          2                3
 0                              Runner  Finish Time  Pace/Mile         Marathon
 1         Belayneh Densamo (Ethiopia)      2:06:50     4:50.3  Rotterdam, 1988
 2           Ronaldo da Costa (Brazil)      2:06:06     4:48.6     Berlin, 1998
 3         Khalid Khannouchi (Morocco)      2:05:42     4:47.7    Chicago, 1999
 4   Khalid Khannouchi (United States)      2:05:38     4:47.5     London, 2002
 5                 Paul Tergat (Kenya)      2:04:55     4:45.9     Berlin, 2003
 6       Haile Gebrselassie (Ethiopia)      2:04:26     4:44.8     Berlin, 2007
 7       Haile Gebrselassie (Ethiopia)      2:03:59     4:43.8     Berlin, 2008
 8               Patrick Makau (Kenya)      2:03:38     4:43.0     Berlin, 2011
 9              Wilson Kipsang (Kenya)      2:03:23     4:42.4     Berlin, 2013
 10             Dennis Kimetto (Kenya)      2:02:57     4:41.4     Berlin, 2014
 11             Eliud Kipchoge (Kenya)      2:01:39     4:38.4     Berlin, 2018
 12             Eliud Kipchoge (Kenya)      2:01:09     4:37.2     Berlin, 2022
 13              Kelvin Kiptum (Kenya)      2:00:35     4:36.0    Chicago, 2023,
                                  0            1          2                3
 0                           Runner  Finish Time  Pace/Mile         Marathon
 1            Tegla Loroupe (Kenya)      2:20:47     5:22.2  Rotterdam, 1998
 2            Tegla Loroupe (Kenya)      2:20:43     5:22.0     Berlin, 1999
 3          Naoko Takahashi (Japan)      2:19:46     5:19.8     Berlin, 2001
 4        Catherine Ndereba (Kenya)      2:18:47     5:17.6    Chicago, 2001
 5  Paula Radcliffe (Great Britain)      2:17:18     5:14.2    Chicago, 2002
 6  Paula Radcliffe (Great Britain)      2:15:25     5:09.9     London, 2003
 7            Brigid Kosgei (Kenya)      2:14:04     5:06.8    Chicago, 2019
 8         Tigist Assefa (Ethiopia)      2:11:53     5:01.8     Berlin, 2023
 9         Ruth Chepngetich (Kenya)      2:09:56     4:47.4    Chicago, 2024]

In [ ]:
#table = pd.concat(tables)
#table

In [ ]:
table = pd.DataFrame()
for t in tables:
  table = pd.concat([table,t].ignore_index = True)
table

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (ipython-input-237631348.py, line 3)

In [2]:
url = "https://api.spacexdata.com/v4/launches"
resp = requests.get(url)
launches = resp.json()
#launches

In [ ]:
launch = pd.DataFrame(launches)
launch.head()

,fairings,links,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,...,date_utc,date_unix,date_local,date_precision,upcoming,cores,auto_update,tbd,launch_library_id,id
0,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'mer...",Engine failure at 33 seconds and loss of vehicle,...,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight'...",True,False,None,5eb87cd9ffd86e000604b32a
1,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'har...",Successful first stage burn and transition to ...,...,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight'...",True,False,None,5eb87cdaffd86e000604b32b
2,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'resi...",Residual stage 1 thrust led to collision betwe...,...,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight'...",True,False,None,5eb87cdbffd86e000604b32c
3,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],Ratsat was carried to orbit on the first succe...,...,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight'...",True,False,None,5eb87cdbffd86e000604b32d
4,"{'reused': False, 'recovery_attempt': False, '...",{'patch': {'small': 'https://images2.imgbox.co...,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],None,...,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight'...",True,False,None,5eb87cdcffd86e000604b32e

In [ ]:
df1_selected = launch[['name','date_utc','success','details','rocket','launch_library_id']]
df1_selected

,name,date_utc,success,details,rocket,launch_library_id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None
...,...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None

In [ ]:
df1_selected= df1_selected.rename(columns={"name":"mission_name","rocket":"rocket_id"})
df1_selected

,mission_name,date_utc,success,details,rocket_id,launch_library_id
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None
...,...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None

In [ ]:
url = "https://api.spacexdata.com/v4/rockets"

res = requests.get(url)
rockets = res.json()
rockets

[{'height': {'meters': 22.25, 'feet': 73},
  'diameter': {'meters': 1.68, 'feet': 5.5},
  'mass': {'kg': 30146, 'lb': 66460},
  'first_stage': {'thrust_sea_level': {'kN': 420, 'lbf': 94000},
   'thrust_vacuum': {'kN': 480, 'lbf': 110000},
   'reusable': False,
   'engines': 1,
   'fuel_amount_tons': 44.3,
   'burn_time_sec': 169},
  'second_stage': {'thrust': {'kN': 31, 'lbf': 7000},
   'payloads': {'composite_fairing': {'height': {'meters': 3.5, 'feet': 11.5},
     'diameter': {'meters': 1.5, 'feet': 4.9}},
    'option_1': 'composite fairing'},
   'reusable': False,
   'engines': 1,
   'fuel_amount_tons': 3.38,
   'burn_time_sec': 378},
  'engines': {'isp': {'sea_level': 267, 'vacuum': 304},
   'thrust_sea_level': {'kN': 420, 'lbf': 94000},
   'thrust_vacuum': {'kN': 480, 'lbf': 110000},
   'number': 1,
   'type': 'merlin',
   'version': '1C',
   'layout': 'single',
   'engine_loss_max': 0,
   'propellant_1': 'liquid oxygen',
   'propellant_2': 'RP-1 kerosene',
   'thrust_to_weight': 96},
  'landing_legs': {'number': 0, 'material': None},
  'payload_weights': [{'id': 'leo',
    'name': 'Low Earth Orbit',
    'kg': 450,
    'lb': 992}],
  'flickr_images': ['https://imgur.com/DaCfMsj.jpg',
   'https://imgur.com/azYafd8.jpg'],
  'name': 'Falcon 1',
  'type': 'rocket',
  'active': False,
  'stages': 2,
  'boosters': 0,
  'cost_per_launch': 6700000,
  'success_rate_pct': 40,
  'first_flight': '2006-03-24',
  'country': 'Republic of the Marshall Islands',
  'company': 'SpaceX',
  'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1',
  'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.',
  'id': '5e9d0d95eda69955f709d1eb'},
 {'height': {'meters': 70, 'feet': 229.6},
  'diameter': {'meters': 3.7, 'feet': 12},
  'mass': {'kg': 549054, 'lb': 1207920},
  'first_stage': {'thrust_sea_level': {'kN': 7607, 'lbf': 1710000},
   'thrust_vacuum': {'kN': 8227, 'lbf': 1849500},
   'reusable': True,
   'engines': 9,
   'fuel_amount_tons': 385,
   'burn_time_sec': 162},
  'second_stage': {'thrust': {'kN': 934, 'lbf': 210000},
   'payloads': {'composite_fairing': {'height': {'meters': 13.1, 'feet': 43},
     'diameter': {'meters': 5.2, 'feet': 17.1}},
    'option_1': 'dragon'},
   'reusable': False,
   'engines': 1,
   'fuel_amount_tons': 90,
   'burn_time_sec': 397},
  'engines': {'isp': {'sea_level': 288, 'vacuum': 312},
   'thrust_sea_level': {'kN': 845, 'lbf': 190000},
   'thrust_vacuum': {'kN': 914, 'lbf': 205500},
   'number': 9,
   'type': 'merlin',
   'version': '1D+',
   'layout': 'octaweb',
   'engine_loss_max': 2,
   'propellant_1': 'liquid oxygen',
   'propellant_2': 'RP-1 kerosene',
   'thrust_to_weight': 180.1},
  'landing_legs': {'number': 4, 'material': 'carbon fiber'},
  'payload_weights': [{'id': 'leo',
    'name': 'Low Earth Orbit',
    'kg': 22800,
    'lb': 50265},
   {'id': 'gto',
    'name': 'Geosynchronous Transfer Orbit',
    'kg': 8300,
    'lb': 18300},
   {'id': 'mars', 'name': 'Mars Orbit', 'kg': 4020, 'lb': 8860}],
  'flickr_images': ['https://farm1.staticflickr.com/929/28787338307_3453a11a77_b.jpg',
   'https://farm4.staticflickr.com/3955/32915197674_eee74d81bb_b.jpg',
   'https://farm1.staticflickr.com/293/32312415025_6841e30bf1_b.jpg',
   'https://farm1.staticflickr.com/623/23660653516_5b6cb301d1_b.jpg',
   'https://farm6.staticflickr.com/5518/31579784413_d853331601_b.jpg',
   'https://farm1.staticflickr.com/745/32394687645_a9c54a34ef_b.jpg'],
  'name': 'Falcon 9',
  'type': 'rocket',
  'active': True,
  'stages': 2,
  'boosters': 0,
  'cost_per_launch': 50000000,
  'success_rate_pct': 98,
  'first_flight': '2010-06-04',
  'country': 'United States',
  'company': 'SpaceX',
  'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_9',
  'description': 'Falcon 9 is a two-stage rocket designed and manufactured by SpaceX for the reliable and safe transport of satellites and the Dragon spacecraft into orbit.',
  'id': '5e9d0d95eda69973a809d1ec'},
 {'height': {'meters': 70, 'feet': 229.6},
  'diameter': {'meters': 12.2, 'feet': 39.9},
  'mass': {'kg': 1420788, 'lb': 3125735},
  'first_stage': {'thrust_sea_level': {'kN': 22819, 'lbf': 5130000},
   'thrust_vacuum': {'kN': 24681, 'lbf': 5548500},
   'reusable': True,
   'engines': 27,
   'fuel_amount_tons': 1155,
   'burn_time_sec': 162},
  'second_stage': {'thrust': {'kN': 934, 'lbf': 210000},
   'payloads': {'composite_fairing': {'height': {'meters': 13.1, 'feet': 43},
     'diameter': {'meters': 5.2, 'feet': 17.1}},
    'option_1': 'dragon'},
   'reusable': False,
   'engines': 1,
   'fuel_amount_tons': 90,
   'burn_time_sec': 397},
  'engines': {'isp': {'sea_level': 288, 'vacuum': 312},
   'thrust_sea_level': {'kN': 845, 'lbf': 190000},
   'thrust_vacuum': {'kN': 914, 'lbf': 205500},
   'number': 27,
   'type': 'merlin',
   'version': '1D+',
   'layout': 'octaweb',
   'engine_loss_max': 6,
   'propellant_1': 'liquid oxygen',
   'propellant_2': 'RP-1 kerosene',
   'thrust_to_weight': 180.1},
  'landing_legs': {'number': 12, 'material': 'carbon fiber'},
  'payload_weights': [{'id': 'leo',
    'name': 'Low Earth Orbit',
    'kg': 63800,
    'lb': 140660},
   {'id': 'gto',
    'name': 'Geosynchronous Transfer Orbit',
    'kg': 26700,
    'lb': 58860},
   {'id': 'mars', 'name': 'Mars Orbit', 'kg': 16800, 'lb': 37040},
   {'id': 'pluto', 'name': 'Pluto Orbit', 'kg': 3500, 'lb': 7720}],
  'flickr_images': ['https://farm5.staticflickr.com/4599/38583829295_581f34dd84_b.jpg',
   'https://farm5.staticflickr.com/4645/38583830575_3f0f7215e6_b.jpg',
   'https://farm5.staticflickr.com/4696/40126460511_b15bf84c85_b.jpg',
   'https://farm5.staticflickr.com/4711/40126461411_aabc643fd8_b.jpg'],
  'name': 'Falcon Heavy',
  'type': 'rocket',
  'active': True,
  'stages': 2,
  'boosters': 2,
  'cost_per_launch': 90000000,
  'success_rate_pct': 100,
  'first_flight': '2018-02-06',
  'country': 'United States',
  'company': 'SpaceX',
  'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_Heavy',
  'description': 'With the ability to lift into orbit over 54 metric tons (119,000 lb)--a mass equivalent to a 737 jetliner loaded with passengers, crew, luggage and fuel--Falcon Heavy can lift more than twice the payload of the next closest operational vehicle, the Delta IV Heavy, at one-third the cost.',
  'id': '5e9d0d95eda69974db09d1ed'},
 {'height': {'meters': 118, 'feet': 387},
  'diameter': {'meters': 9, 'feet': 30},
  'mass': {'kg': 1335000, 'lb': 2943000},
  'first_stage': {'thrust_sea_level': {'kN': 128000, 'lbf': 28775544},
   'thrust_vacuum': {'kN': 138000, 'lbf': 31023634},
   'reusable': True,
   'engines': 37,
   'fuel_amount_tons': 3300,
   'burn_time_sec': None},
  'second_stage': {'thrust': {'kN': 1957, 'lbf': 440000},
   'payloads': {'composite_fairing': {'height': {'meters': None, 'feet': None},
     'diameter': {'meters': None, 'feet': None}},
    'option_1': 'Spaceship'},
   'reusable': True,
   'engines': 6,
   'fuel_amount_tons': 1200,
   'burn_time_sec': None},
  'engines': {'isp': {'sea_level': 330, 'vacuum': 380},
   'thrust_sea_level': {'kN': 1780, 'lbf': 400000},
   'thrust_vacuum': {'kN': 1960, 'lbf': 440000},
   'number': 37,
   'type': 'raptor',
   'version': '',
   'layout': None,
   'engine_loss_max': None,
   'propellant_1': 'liquid oxygen',
   'propellant_2': 'liquid methane',
   'thrust_to_weight': 107},
  'landing_legs': {'number': 6, 'material': 'stainless steel'},
  'payload_weights': [{'id': 'leo',
    'name': 'Low Earth Orbit',
    'kg': 150000,
    'lb': 330000},
   {'id': 'mars', 'name': 'Mars Orbit', 'kg': 100000, 'lb': 220000},
   {'id': 'moon', 'name': 'Moon Orbit', 'kg': 100000, 'lb': 220000}],
  'flickr_images': ['https://live.staticflickr.com/65535/48954138962_ee541e6755_b.jpg',
   'https://live.staticflickr.com/65535/48953946911_e60c5bcc5c_b.jpg',
   'https://live.staticflickr.com/65535/48954138922_9c42173f08_b.jpg',
   'https://live.staticflickr.com/65535/48953947006_313f01ec93_b.jpg'],
  'name': 'Starship',
  'type': 'rocket',
  'active': False,
  'stages': 2,
  'boosters': 0,
  'cost_per_launch': 7000000,
  'success_rate_pct': 0,
  'first_flight': '2021-12-01',
  'country': 'United States',
  'company': 'SpaceX',
  'wikipedia': 'https://en.wikipedia.org/wiki/SpaceX_Starship',
  'description': 'Starship and Super Heavy Rocket represent a fully reusable transportation system designed to service all Earth orbit needs as well as the Moon and Mars. This two-stage vehicle — composed of the Super Heavy rocket (booster) and Starship (ship) — will eventually replace Falcon 9, Falcon Heavy and Dragon.',
  'id': '5e9d0d96eda699382d09d1ee'}]

In [ ]:
rocket = pd.DataFrame(rockets)
rocket.head()

,height,diameter,mass,first_stage,second_stage,engines,landing_legs,payload_weights,flickr_images,name,...,stages,boosters,cost_per_launch,success_rate_pct,first_flight,country,company,wikipedia,description,id
0,"{'meters': 22.25, 'feet': 73}","{'meters': 1.68, 'feet': 5.5}","{'kg': 30146, 'lb': 66460}","{'thrust_sea_level': {'kN': 420, 'lbf': 94000}...","{'thrust': {'kN': 31, 'lbf': 7000}, 'payloads'...","{'isp': {'sea_level': 267, 'vacuum': 304}, 'th...","{'number': 0, 'material': None}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...","[https://imgur.com/DaCfMsj.jpg, https://imgur....",Falcon 1,...,2,0,6700000,40,2006-03-24,Republic of the Marshall Islands,SpaceX,https://en.wikipedia.org/wiki/Falcon_1,The Falcon 1 was an expendable launch system p...,5e9d0d95eda69955f709d1eb
1,"{'meters': 70, 'feet': 229.6}","{'meters': 3.7, 'feet': 12}","{'kg': 549054, 'lb': 1207920}","{'thrust_sea_level': {'kN': 7607, 'lbf': 17100...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 4, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm1.staticflickr.com/929/2878733830...,Falcon 9,...,2,0,50000000,98,2010-06-04,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_9,Falcon 9 is a two-stage rocket designed and ma...,5e9d0d95eda69973a809d1ec
2,"{'meters': 70, 'feet': 229.6}","{'meters': 12.2, 'feet': 39.9}","{'kg': 1420788, 'lb': 3125735}","{'thrust_sea_level': {'kN': 22819, 'lbf': 5130...","{'thrust': {'kN': 934, 'lbf': 210000}, 'payloa...","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...","{'number': 12, 'material': 'carbon fiber'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://farm5.staticflickr.com/4599/385838292...,Falcon Heavy,...,2,2,90000000,100,2018-02-06,United States,SpaceX,https://en.wikipedia.org/wiki/Falcon_Heavy,With the ability to lift into orbit over 54 me...,5e9d0d95eda69974db09d1ed
3,"{'meters': 118, 'feet': 387}","{'meters': 9, 'feet': 30}","{'kg': 1335000, 'lb': 2943000}","{'thrust_sea_level': {'kN': 128000, 'lbf': 287...","{'thrust': {'kN': 1957, 'lbf': 440000}, 'paylo...","{'isp': {'sea_level': 330, 'vacuum': 380}, 'th...","{'number': 6, 'material': 'stainless steel'}","[{'id': 'leo', 'name': 'Low Earth Orbit', 'kg'...",[https://live.staticflickr.com/65535/489541389...,Starship,...,2,0,7000000,0,2021-12-01,United States,SpaceX,https://en.wikipedia.org/wiki/SpaceX_Starship,Starship and Super Heavy Rocket represent a fu...,5e9d0d96eda699382d09d1ee

In [ ]:
df2_selected = rocket[['id','name','country','company','cost_per_launch']]
df2_selected

,id,name,country,company,cost_per_launch
0,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
1,5e9d0d95eda69973a809d1ec,Falcon 9,United States,SpaceX,50000000
2,5e9d0d95eda69974db09d1ed,Falcon Heavy,United States,SpaceX,90000000
3,5e9d0d96eda699382d09d1ee,Starship,United States,SpaceX,7000000

In [ ]:
final_data = df1_selected.merge(df2_selected,left_on='rocket_id',right_on='id',how ='left')
final_data

,mission_name,date_utc,success,details,rocket_id,launch_library_id,id,name,country,company,cost_per_launch
0,FalconSat,2006-03-24T22:30:00.000Z,False,Engine failure at 33 seconds and loss of vehicle,5e9d0d95eda69955f709d1eb,None,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
1,DemoSat,2007-03-21T01:10:00.000Z,False,Successful first stage burn and transition to ...,5e9d0d95eda69955f709d1eb,None,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
2,Trailblazer,2008-08-03T03:34:00.000Z,False,Residual stage 1 thrust led to collision betwe...,5e9d0d95eda69955f709d1eb,None,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
3,RatSat,2008-09-28T23:15:00.000Z,True,Ratsat was carried to orbit on the first succe...,5e9d0d95eda69955f709d1eb,None,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
4,RazakSat,2009-07-13T03:35:00.000Z,True,None,5e9d0d95eda69955f709d1eb,None,5e9d0d95eda69955f709d1eb,Falcon 1,Republic of the Marshall Islands,SpaceX,6700000
...,...,...,...,...,...,...,...,...,...,...,...
200,Transporter-6,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,5e9d0d95eda69973a809d1ec,Falcon 9,United States,SpaceX,50000000
201,TTL-1,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,5e9d0d95eda69973a809d1ec,Falcon 9,United States,SpaceX,50000000
202,WorldView Legion 1 & 2,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,5e9d0d95eda69973a809d1ec,Falcon 9,United States,SpaceX,50000000
203,Viasat-3 & Arcturus,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69974db09d1ed,None,5e9d0d95eda69974db09d1ed,Falcon Heavy,United States,SpaceX,90000000
204,O3b mPower 3.4,2022-12-01T00:00:00.000Z,None,None,5e9d0d95eda69973a809d1ec,None,5e9d0d95eda69973a809d1ec,Falcon 9,United States,SpaceX,50000000

In [ ]:
final_data.shape

(205, 11)

In [ ]:
final_data = df1_selected.merge(df2_selected,left_on='rocket_id',right_on='id',how ='inner')
final_data.shape

(205, 11)